/opt/ros/noetic/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <class 'genmsg.base.InvalidMsgSpec'>: /home/mbrummelhuis/msc_thesis/catkin_ws/src/impedance/msg/pw.msg: Duplicate field names in message: ['x', 'y', 'z', 'r', 'p', 'y']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/genmsg/msg_loader.py", line 287, in load_msg_from_file
    return load_msg_from_string(msg_context, text, full_name)
  File "/usr/local/lib/python3.8/dist-packages/genmsg/msg_loader.py", line 269, in load_msg_from_string
    spec = MsgSpec(types, names, constants, text, full_name, package_name)
  File "/usr/local/lib/python3.8/dist-packages/genmsg/msgs.py", line 251, in __init__
    raise InvalidMsgSpec("Duplicate field names in message: %s"%names)
genmsg.base.InvalidMsgSpec: Duplicate field names in message: ['x', 'y', 'z', 'r', 'p', 'y']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 3303, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 3301, in main
    invoke(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 3284, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 2295, in wrap
    self.fail(e)
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 2284, in wrap
    callable(*args)
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/local/lib/python3.8/dist-packages/em.py", line 2596, in execute
    _exec(statements, self.globals, locals)
  File "<string>", line 38, in <module>
  File "/usr/local/lib/python3.8/dist-packages/genmsg/deps.py", line 45, in find_msg_dependencies_with_type
    spec = genmsg.msg_loader.load_msg_from_file(msg_context, msg_file, full_type_name)
  File "/usr/local/lib/python3.8/dist-packages/genmsg/msg_loader.py", line 289, in load_msg_from_file
    raise InvalidMsgSpec('%s: %s'%(file_path, e))
genmsg.base.InvalidMsgSpec: /home/mbrummelhuis/msc_thesis/catkin_ws/src/impedance/msg/pw.msg: Duplicate field names in message: ['x', 'y', 'z', 'r', 'p', 'y']
[31m[1mCMake Error[0m at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/home/mbrummelhuis/msc_thesis/catkin_ws/build/impedance/catkin_generated/env_cached.sh
  "/usr/bin/python3" "/usr/local/lib/python3.8/dist-packages/em.py"
  "--raw-errors" "-F"
  "/home/mbrummelhuis/msc_thesis/catkin_ws/build/impedance/cmake/impedance-genmsg-context.py"
  "-o"
  "/home/mbrummelhuis/msc_thesis/catkin_ws/build/impedance/cmake/impedance-genmsg.cmake"
  "/opt/ros/noetic/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
[36mCall Stack (most recent call first):[0m
  /opt/ros/noetic/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/noetic/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  CMakeLists.txt:73 (generate_messages)


make: *** [Makefile:618: cmake_check_build_system] Error 1
